const crypto = require('crypto');

function b64url(buf) {
  return buf.toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function genHash(password) {
  const salt = crypto.randomBytes(16);
  const derived = crypto.pbkdf2Sync(password, salt, 100000, 32, 'sha256');
  return `${b64url(salt)}.${b64url(derived)}`;
}

const username = process.argv[2] || 'admin';
const password = process.argv[3] || 'admin123';
const email = process.argv[4] || 'admin@example.com';
const name = process.argv[5] || 'Site Admin';

const hash = genHash(password);

console.log('-- Admin user seed (auto-generated by tools/gen_admin_hash.cjs)');
console.log(`INSERT INTO users (email, username, name, password_hash, role, is_active) VALUES ('${email}','${username}','${name}','${hash}','admin',1);`);
console.log("-- Profile for admin (links to the inserted user)");
console.log(`INSERT INTO profiles (user_id, bio, profile_photo) VALUES ((SELECT id FROM users WHERE username='${username}'), 'Site administrator', NULL);`);
